version: '3'
services:
  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper:latest
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    ports:
      - 22181:2181

  kafka:
    container_name: kafka
    depends_on:
      - zookeeper
    image: apache/kafka:latest
    ports:
      - 9092:9092
      
